### ISSUE TITLE
Abaqus V2019 -> V2020

### ISSUE THREAD

**Issue by haiiliin** [haiiliin/abqpy#145]
Update API changes from Abaqus V2019 to V2020
- [x] #153 
- [x] #154 
- [x] Remove #152 in V2016-V2019 but keep it in V2020 #155
- [x] Remove #160 in V2016-V2019 but keep it in V2020 
- [x] Remove #164 in V2016-V2019 but keep it in V2020 #168
- [x] #169 
- [x] #Remove #172 in V2016-V2019 but keep it in V2020 #171
- [x] #181 
- [x] Create V2020 branch
- [x] #182
