### ISSUE TITLE
Abaqus V2017 -> V2018

### ISSUE THREAD

**Issue by haiiliin** [haiiliin/abqpy#20]
Update API changes from Abaqus V2017 to V2018
- [x] #53 
- [x] Remove #56 and #57 for V2016 and V2017 but keep them in V2018
- [x] Remove #60 but keep it in V2018
- [x] Remove #61 but keep it in V2018, Update #62 
- [x] Remove #65 but keep it in V2018, update #66
- [x] #68 
- [x] #69 
- [x] #70 
- [x] #71 
- [x] #72 
- [x] #73 
- [x] Remove #75 but keep it in V2018, Update #74
- [x] #77 
- [x] #78, #84
- [x] Remove #79 but keep it in V2018
- [x] #80 
- [x] #82 
- [x] #85 
- [x] Create V2018 branch
- [x] #88
