### ISSUE TITLE
Abaqus V2018 -> V2019

### ISSUE THREAD

**Issue by haiiliin** [haiiliin/abqpy#89]
Update API changes from Abaqus V2018 to V2019
- [x] #97 
- [x] #98 
- [x] #99 
- [x] #100 
- [x] Remove #104 in V2016-V2018 but keep it in V2019 #107
- [x] Remove #108 
- [x] #112 
- [x] #113, and backport to V2016-V2018
- [x] #117, and backport to V2016-V2018
- [x] Remove #121 but keep it in V2019
- [x] #124 
- [x] Remove #125 in V2016-V2018 but keep it in V2019 #126, and Add #130 in V2016-V2018
- [x] #133, #134
- [x] Remove #135 in V2016-V2018 but keep it in V2019
- [x] #140 
- [x] Create V2019 branch
- [x] #144
